//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invetory
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Color { get; set; }
        public string Sizes { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
