//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderStatus = new HashSet<OrderStatus>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<bool> isCancel { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    
        public virtual Carts Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatus> OrderStatus { get; set; }
    }
}
